### ISSUE TITLE
请教：upstream 配置health-checks报错

### ISSUE THREAD

**Issue by 18wu** [qianyugang/kong-docs-cn#6]
大量报
[lua] balancer.lua:316: [healthchecks] failed setting peer status (upstream: 3eb0b3ee-3322-4509-bc9b-ad5c19351aed:testHealthy): no peer found by name 'dcdev.definesys.cn' and address 39.103.230.188:30816, context: ngx.timer
upstream如下:{
    "client_certificate": null,
    "id": "061c28de-a59e-4ef8-b353-b6602bfebb81",
    "hash_on_header": null,
    "healthchecks": {
        "passive": {
            "type": "http",
            "unhealthy": {
                "http_statuses": [
                    429,
                    500,
                    503
                ],
                "tcp_failures": 0,
                "timeouts": 0,
                "http_failures": 0
            },
            "healthy": {
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308
                ],
                "successes": 0
            }
        },
        "threshold": 0,
        "active": {
            "type": "http",
            "http_path": "/data",
            "https_sni": null,
            "timeout": 2,
            "healthy": {
                "interval": 10,
                "http_statuses": [
                    200,
                    302
                ],
                "successes": 2
            },
            "unhealthy": {
                "interval": 3,
                "tcp_failures": 1,
                "timeouts": 1,
                "http_failures": 0,
                "http_statuses": [
                    429,
                    404,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505
                ]
            },
            "https_verify_certificate": false,
            "concurrency": 10
        }
    },
    "hash_fallback_header": null,
    "hash_on": "none",
    "created_at": 1637840050,
    "hash_on_cookie": null,
    "hash_on_cookie_path": "/",
    "hash_fallback": "none",
    "algorithm": "round-robin",
    "tags": null,
    "name": "testHealthy",
    "host_header": null,
    "slots": 1000
}

**Comment by qianyugang** [comment]
[#5589](https://github.com/Kong/kong/issues/5589) 看一下是不是和这个问题一样
